WorkOrderManagementSystem/WorkOrderManagementSystem/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkOrderManagementSystem.Controllers
{
    public class CustomersController : Controller
    {
        private Manager m = new Manager();
        // GET: Customers
        public ActionResult Index()
        {
            return View(m.CustomersGetAllWithBicycles());
        }

        [Route("customers/customerCompletedSearch/{searchExp}")]
        public ActionResult CustomerSearch(string searchExp)
        {
            var found = m.CustomerGetBySearchString(searchExp);
            if (found == null) { found = new List<CustomerGeneral>(); }
            return PartialView("_CustomerIndexTable", found);
        }

        // GET: Customers/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        public ActionResult Details(int? Id)
        {
            var it = m.CustomerDetailsById(Id.GetValueOrDefault());
            if (it == null)
            {

                return HttpNotFound();
            }
            else
            {
                return View(it);
            }
        }

        // GET: Customers/Create *** modified to add customer
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create ***modified to add customer
        [HttpPost]
        public ActionResult Create(CustomerAdd newItem)
        {
            //validate the input
            if (!ModelState.IsValid) {
                return View(newItem);
            }

            //process the inputted data from form
            var addedCust = m.CustomerAddNew(newItem);

            if (addedCust == null)
            {

                return View(newItem);

            }
            else {

                return RedirectToAction("Details", new { id = addedCust.Id });
            }

            
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            // Attempt to fetch the matching object

            var form = m.CustomerGetByIdForEdit(id);

            if (form == null)
            {
                return HttpNotFound();
            }
            else
            {
               

                return View(form);
            }
        }

        // POST: Customers/Edit/5
        [HttpPost]
        public ActionResult Edit(int? id, CustomerEdit newItem)
        {
            // Validate the input
            if (!ModelState.IsValid)
            {
                // Our "version 1" approach is to display the "edit form" again
                return RedirectToAction("edit", new { id = newItem.Id });
            }

            if (id.GetValueOrDefault() != newItem.Id)
            {
                // This appears to be data tampering, so redirect the user away
                return RedirectToAction("index");
            }

            // Attempt to do the update
            var editedItem = m.CustomerEdit(newItem);

            if (editedItem == null)
            {
                // There was a problem updating the object
                // Our "version 1" approach is to display the "edit form" again
                return RedirectToAction("edit", new { id = newItem.Id });
            }
            else
            {
                // Show the details view, which will have the updated data
                return RedirectToAction("details", new { id = newItem.Id });
            }
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Customers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bicycles/Create
        [Route("Customers/AddBicycle/{id}")]
        public ActionResult AddBicycle(int? id)
        {
            var c = m.CustomerGetByIdMaybe(id.GetValueOrDefault());

            if(c == null)
            {
                return HttpNotFound();
            }
            else
            {
                var form = new BicycleAddForCreateForm();
                form.CustomerId = c.Id;
                form.CustomerFirstName = c.FirstName;
                form.CustomerLastName = c.LastName;
                form.CustomerEmail = c.Email;
                form.CustomerPhone = c.Phone;
                return View(form);
            }

        }

        // POST: Bicycles/Create
        [Route("Customers/AddBicycle/{id}")]
        [HttpPost]
        public ActionResult AddBicycle(BicycleAddForCreate newItem)
        {

            //validate the input
            if (!ModelState.IsValid)
            {
                return View(newItem);
            }

            //process the inputted data from form
            var addedBike = m.BicycleAddNew(newItem);

            if (addedBike == null)
            {
                return View(newItem);
            }
            else
            {
                return RedirectToAction("Details", "Bicycles", new { id = addedBike.Id });
            }
        }

       [Route("Customers/getbikesforcustomer/{Id}")]
       public ActionResult GetBikesForCustomer(int? Id)
        {
            var foundThem = m.BicycleGetByCustIdForDetails(Id.Value);
                        if (foundThem == null)
                        { return HttpNotFound();
                        }
                      else {
                            return PartialView("_NBikeList", foundThem);
                        }
                  }

        [Route("Customers/getworkordersforcustomer/{Id}")]
        public ActionResult GetWorkOrdersForCustomer(int? Id)
        {
            var customerWorkOrders = m.WorkOrdersByCustomerId(Id.Value);
                       if (customerWorkOrders == null)
            {
                           return HttpNotFound();
                       }
                       else { return PartialView("_WorkOrdersByCustomer", customerWorkOrders); };
           
            }

        [Route("Customers/getinvoicesforcustomer/{Id}")]
        public ActionResult GetInvoicesForCustomer(int? Id) {
            var customerInvoices = m.GetInvoiceByCustId(Id.Value);
            if (customerInvoices == null)
            {
                return HttpNotFound();
            }
            else {
                //problem seems to be here < --- get internal server error here....
                return PartialView("_InvoicesForCustomer", customerInvoices);
            }
        }
    }
}

WorkOrderManagementSystem/WorkOrderManagementSystem/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkOrderManagementSystem.Controllers
{
    public class InvoiceController : Controller
    {
        private Manager m = new Manager();

        // GET: Invoice
        public ActionResult Index()
        {
            var b = m.GetAllInvoices();
            return View(b);
        }

        //Get: All unpaid Invoices
        public ActionResult GetAllUnPaidInvoices()
        {
            return View(m.GetAllUnpaidInvoices());
        }

        //Get: All paid Invoices
        public ActionResult GetAllPaidInvoices() {
            return View(m.GetAllPaidInvoices());
        }

        // GET: Invoice/Details/5
        public ActionResult Details(int? id)
        {
            //create a method to get Invoice Details by Id and then change this up
            var it = m.InvoiceDetailsById(id.GetValueOrDefault());
            if (it == null)
            {

                return HttpNotFound();
            }
            else
            {
                return View(it);
            }
        }

        // GET: Invoice/Create <--use this to create invoices
        //need to call action method
        [Route ("Invoice/Create/{id}")]
        public ActionResult Create(int? id)
        {

            //checks for oldInvoice - if there is one, return it is one option. 
            //var oldInv = m.InvoiceDetailsById(id.GetValueOrDefault());
            if (id ==null || id <=0)//used to check modelState
            {
                //return the user to the work order details of that work order instead
                return RedirectToAction("../WorkOrders/GetAllCompletedWO");
            }

            
            //manager method first checks if workorder exists, and may return existing instead of creating new one
            //TODO: need to pass error messages to new redirectpage if it returns null
            var createdInvoice = m.InvoiceCreateFromCompletedWO(id.Value);
            
            if (createdInvoice.Id == 0)
            {
                
                //return to list of invoices 
                //make invoice details a partial and call it from the view. 
                //will allow it to refresh easier
              return RedirectToAction("_InvoiceList");//needs error message on page
            }
            else
            {
                
                        return RedirectToAction("Details", new { id = createdInvoice.Id });
                
            }

            
        }

        // POST: Invoice/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Invoice/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Invoice/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Invoice/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Invoice/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Route("Invoice/changepaidstatus/{id}")]
        public ActionResult ChangePaidStatus(int id) {

            //need different method here to call from manager to change the paid stat on ds.
            var theOne = m.InvoiceChangePaidStatusById(id);
            
        return PartialView("_InvoiceMoreDetailed", theOne);
            
        }
    }
}

WorkOrderManagementSystem/WorkOrderManagementSystem/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkOrderManagementSystem.Controllers
{
    public class ModelController : Controller
    {
        private Manager m = new Manager();
        // GET: Model
        public ActionResult Index()
        {
            return View(m.ModelsGetAll());
        }

        // GET: Model/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Model/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Model/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Manufacturer/Edit/5
        public ActionResult Edit(int? id)
        {
            var form = m.ModelGetByIdForEdit(id);

            if (form == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(form);
            }
        }

        // POST: Manufacturer/Edit/5
        [HttpPost]
        public ActionResult Edit(int? id, ModelEdit newItem)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("edit", new { id = newItem.Id });
            }

            if (id.GetValueOrDefault() != newItem.Id)
            {
                return RedirectToAction("index");
            }

            var editedItem = m.ModelEdit(newItem);

            if (editedItem == null)
            {
                return RedirectToAction("edit", new { id = newItem.Id });
            }
            else
            {
                return RedirectToAction("index");
            }
        }

        // GET: Model/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Model/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WorkOrderManagementSystem/WorkOrderManagementSystem/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkOrderManagementSystem.Controllers
{
    public class ReportsController : Controller
    {
        private Manager m = new Manager();
        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        [Route("reports/serviceitempopularity")]
        public ActionResult ServiceItemPopularity()
        {
            var sipopularityreport = m.ReportServiceItemPopularity();
            return View(sipopularityreport);
        }
    public ActionResult ManufacturerPopularity()
    {
      var manupopularityreport = m.ReportManufacturerPopularity();
      return View(manupopularityreport);
    }

    [Route("reports/mechanicreports")]
    public ActionResult MechanicReports()
    {
      var list = m.ReportMechAsgntWeek();
      return View(list);
    }

    [Route("reports/MechAsgtWeekly")]
    public ActionResult MechAsgtWeekly()
    {
      var list = m.ReportMechAsgntWeek();
      return PartialView("_MechAsgtWeek", list);
    }
    [Route("reports/MechAsgtMonthly")]
    public ActionResult MechAsgtMonthly()
    {
      var list = m.ReportMechAsgntMonth();
      return PartialView("_MechAsgtWeek", list);
    }
      
    [Route("reports/MechAsgtYearly")]
    public ActionResult MechAsgtYearly()
    {
      var list = m.ReportMechAsgntYear();
    return PartialView("_MechAsgtWeek", list);

  }

    public ActionResult InvoiceReports()
    {
      var invReport = m.ReportOnInvoices();
      return View(invReport);
    }
  //// GET: Reports/Details/5
  //public ActionResult Details(int id)
  //{
  //    return View();
  //}

  //// GET: Reports/Create
  //public ActionResult Create()
  //{
  //    return View();
  //}

  //// POST: Reports/Create
  //[HttpPost]
  //public ActionResult Create(FormCollection collection)
  //{
  //    try
  //    {
  //        // TODO: Add insert logic here

  //        return RedirectToAction("Index");
  //    }
  //    catch
  //    {
  //        return View();
  //    }
  //}

  //// GET: Reports/Edit/5
  //public ActionResult Edit(int id)
  //{
  //    return View();
  //}

  //// POST: Reports/Edit/5
  //[HttpPost]
  //public ActionResult Edit(int id, FormCollection collection)
  //{
  //    try
  //    {
  //        // TODO: Add update logic here

  //        return RedirectToAction("Index");
  //    }
  //    catch
  //    {
  //        return View();
  //    }
  //}

  //// GET: Reports/Delete/5
  //public ActionResult Delete(int id)
  //{
  //    return View();
  //}

  //// POST: Reports/Delete/5
  //[HttpPost]
  //public ActionResult Delete(int id, FormCollection collection)
  //{
  //    try
  //    {
  //        // TODO: Add delete logic here

  //        return RedirectToAction("Index");
  //    }
  //    catch
  //    {
  //        return View();
  //    }
  //}
}
}

WorkOrderManagementSystem/WorkOrderManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OSFK-WOMS </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*@Scripts.Render("~/bundles/bootstrap")*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Work Order Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Work Orders
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Start New Work Order", "Create", "WorkOrders")</li>
                            <li>@Html.ActionLink("View Active", "Index", "WorkOrders")</li>

                            <li>@Html.ActionLink("View Completed", "GetAllCompletedWO", "WorkOrders")</li>
                            <li>@Html.ActionLink("View All", "GetAllWorkorders", "WorkOrders")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Customers
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Create New Customer", "Create", "Customers")</li>
                            <li>@Html.ActionLink("View All Customers", "Index", "Customers")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Mechanics
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            @*Mechanic Menu*@
                            <li>@Html.ActionLink("Create New Mechanic", "Create", "Mechanics")</li>
                            <li>@Html.ActionLink("View All Mechanics", "Index", "Mechanics")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Bicycles
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            @*Bicycles Menu*@
                            <li>@Html.ActionLink("View All Bicycles", "Index", "BikeModels")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Invoices
                            <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            @*Invoice Menu*@
                            <li>@Html.ActionLink("View All Invoices", "Index", "Invoice")</li>
                            @*rejection not implemented yet*@
                            <li>@Html.ActionLink("Outstanding Invoices", "GetAllUnPaidInvoices", "Invoice")</li>
                            <li>@Html.ActionLink("Paid Invoices", "GetAllPaidInvoices", "Invoice")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Models / Manufacturers
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("List of Manufacturers", "Index", "Manufacturers")</li>
                            <li>@Html.ActionLink("List of Models", "Index", "Model")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                           Reports
                            <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            @*Reports Menu*@
                            <li>@Html.ActionLink("View All Reports", "Index", "Reports")</li>
                            @*rejection not implemented yet*@
                            <li>@Html.ActionLink("Manufacturer: By popularity", "ManufacturerPopularity", "Reports")</li>
                            <li>@Html.ActionLink("Service Items: By Popularity", "ServiceItemPopularity", "Reports")</li>
                            <li>@Html.ActionLink("Mechanic Report", "MechanicReports", "Reports")</li>
                            <li>@Html.ActionLink("Invoice Report", "InvoiceReports", "Reports")</li>
                        </ul>
                    </li>
                </ul>
               @* @Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Group 9(Michael Overall, Tanvir Sarkar, Dan Foster, Igor Krasnyanskiy)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>