WorkOrderManagementSystem/WorkOrderManagementSystem/Controllers/MechanicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkOrderManagementSystem.Controllers
{
  public class MechanicsController : Controller
  {
    private Manager m = new Manager();

    // GET: Mechanics
    public ActionResult Index()
    {
      return View(m.MechanicsGetWithWorkOrders());
    }

    // GET: Mechanics/Details/5
    public ActionResult Details(int? id)
    {
      var it = m.MechanicGetByIdWithWorkOrders(id.GetValueOrDefault());
      if (it == null)
      {

        return HttpNotFound();
      }
      else
      {
        return View(it);
      }
    }

    // GET: Mechanics/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: Mechanics/Create
    [HttpPost]
    public ActionResult Create(MechanicBase newMech)
    {
            if (!ModelState.IsValid) {
                return View(newMech);
            }

            bool isUnique = m.isMechanicUnique(newMech);

            if (!isUnique)
            {
                string errorMsg = "Duplicate entry. That phone or email already exists.";
                @TempData["SubmitErrorMsg"] = errorMsg;
                return View(newMech);
            }

            var addedMech = m.MechanicAddNew(newMech);

            if (addedMech == null)
            {

                return View(newMech);
            }
            else {
                return RedirectToAction("Details", new { id = addedMech.Id });
            }
    }

    // GET: Mechanics/Edit/5
    public ActionResult Edit(int? id)
    {
            var o = m.MechanicGetById(id.GetValueOrDefault());
            if (o == null)
            {
                return HttpNotFound();
            }
            else {
                var editForm = m.mapper.Map<MechanicBase>(o);
                return View(editForm);
            }

    }

        // POST: Mechanics/Edit/5
        [HttpPost]
        public ActionResult Edit(int? id, MechanicBase newItem)
        {
            //validate the input
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Edit", new { id = newItem.Id });
            }

            if (id.GetValueOrDefault() != newItem.Id)
            {

                return RedirectToAction("index");
            }

            bool isUnique = m.isMechanicUnique(newItem);

            if (!isUnique)
            {
                string errorMsg = "Duplicate entry. That phone or email already exists. Resetting info.";
                @TempData["SubmitErrorMsg"] = errorMsg;
                return RedirectToAction("Edit", new { id = newItem.Id });
            }

            //attempt to do the update
            var editedItem = m.MechanicEdit(newItem);

            if (editedItem == null)
            {
                //there is a problem updating the object
                return RedirectToAction("Edit", new { id = newItem.Id });

            }
            else
            {
                return RedirectToAction("Details", new { id = newItem.Id });
            }
            
        }

        // GET: Mechanics/Delete/5
        public ActionResult Delete(int id)
    {
      return View();
    }

    // POST: Mechanics/Delete/5
    [HttpPost]
    public ActionResult Delete(int id, FormCollection collection)
    {
      try
      {
        // TODO: Add delete logic here

        return RedirectToAction("Index");
      }
      catch
      {
        return View();
      }
    }
  }
}

WorkOrderManagementSystem/WorkOrderManagementSystem/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkOrderManagementSystem.Controllers
{
    public class ReportsController : Controller
    {
        private Manager m = new Manager();
        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        [Route("reports/serviceitempopularity")]
        public ActionResult ServiceItemPopularity()
        {
            var sipopularityreport = m.ReportServiceItemPopularity();
            return View(sipopularityreport);
        }
    public ActionResult ManufacturerPopularity()
    {
      var manupopularityreport = m.ReportManufacturerPopularity();
      return View(manupopularityreport);
    }

    [Route("reports/mechanicreports")]
    public ActionResult MechanicReports()
    {
      var list = m.ReportMechAsgntWeek();
      return View(list);
    }

    [Route("reports/MechAsgtWeekly")]
    public ActionResult MechAsgtWeekly()
    {
      var list = m.ReportMechAsgntWeek();
      return PartialView("_MechAsgtWeek", list);
    }
    [Route("reports/MechAsgtMonthly")]
    public ActionResult MechAsgtMonthly()
    {
      var list = m.ReportMechAsgntMonth();
      return PartialView("_MechAsgtWeek", list);
    }
      
    [Route("reports/MechAsgtYearly")]
    public ActionResult MechAsgtYearly()
    {
      var list = m.ReportMechAsgntYear();
    return PartialView("_MechAsgtWeek", list);

  }

    public ActionResult InvoiceReports()
    {
      var invReport = m.ReportOnInvoices();
      return View(invReport);
    }
  //// GET: Reports/Details/5
  //public ActionResult Details(int id)
  //{
  //    return View();
  //}

  //// GET: Reports/Create
  //public ActionResult Create()
  //{
  //    return View();
  //}

  //// POST: Reports/Create
  //[HttpPost]
  //public ActionResult Create(FormCollection collection)
  //{
  //    try
  //    {
  //        // TODO: Add insert logic here

  //        return RedirectToAction("Index");
  //    }
  //    catch
  //    {
  //        return View();
  //    }
  //}

  //// GET: Reports/Edit/5
  //public ActionResult Edit(int id)
  //{
  //    return View();
  //}

  //// POST: Reports/Edit/5
  //[HttpPost]
  //public ActionResult Edit(int id, FormCollection collection)
  //{
  //    try
  //    {
  //        // TODO: Add update logic here

  //        return RedirectToAction("Index");
  //    }
  //    catch
  //    {
  //        return View();
  //    }
  //}

  //// GET: Reports/Delete/5
  //public ActionResult Delete(int id)
  //{
  //    return View();
  //}

  //// POST: Reports/Delete/5
  //[HttpPost]
  //public ActionResult Delete(int id, FormCollection collection)
  //{
  //    try
  //    {
  //        // TODO: Add delete logic here

  //        return RedirectToAction("Index");
  //    }
  //    catch
  //    {
  //        return View();
  //    }
  //}
}
}

WorkOrderManagementSystem/WorkOrderManagementSystem/Views/Reports/Index.cshtml
@{
    ViewBag.Title = "Reports";
}

<h2>Reports</h2>

<table class="table">
    <tr>
        <th>Category</th>
        <th>Report Name</th>
        <th>Link</th>
    </tr>
    <tr>
        <td>Manufacturer</td>
        <td>Manufacturer Popularity</td>
        <td>@Html.ActionLink("View", "ManufacturerPopularity")</td>
    </tr>
    <tr>
        <td>Service Item</td>
        <td>Service Item Popularity</td>
        <td>@Html.ActionLink("View", "ServiceItemPopularity")</td>
    </tr>
  <tr>
    <td>Mechanic</td>
    <td>Mechanic Work Order Assignments (last week/month/year)</td>
    <td>@Html.ActionLink("View", "MechanicReports")</td>
  </tr>
  <tr>
    <td>Invoices</td>
    <td>Invoice Stats</td>
    <td>@Html.ActionLink("View", "InvoiceReports")</td>
  </tr>
</table>

WorkOrderManagementSystem/WorkOrderManagementSystem/Views/Reports/InvoiceReports.cshtml
@model WorkOrderManagementSystem.Controllers.InvoiceReport

@{
  ViewBag.Title = "InvoiceReports";
}

<h2>InvoiceReports</h2>

<div>
  <h4>InvoiceReport</h4>
  <hr />
  <table class="table-striped">


    <tr>
      <td>
        <b>Average Revenue This Week:</b>
      </td>
      <td>
        @Html.DisplayFor(model => model.avgRevenueThisWeek)
      </td>
    </tr>

    <tr>
      <td><b>Number of Invoices This Week:</b></td>
      <td>@Html.DisplayFor(model => model.numThisWeek)</td>
    </tr>

   
    <tr>
    <td><b>Average Revenue This Month:</b></td>

    <td>@Html.DisplayFor(model => model.avgRevenueThisMonth)</td>
    </tr>

    <tr>
      <td><b>Number of Invoices This Month:</b></td>
      <td>
        @Html.DisplayFor(model => model.numThisMonth)
      </td>
    </tr>

    <tr>
      <td>
        <b>Average Revenue This Year:</b>
      </td>

      <td>
        @Html.DisplayFor(model => model.avgRevenueThisYear)
      </td>
    </tr>

    <tr>
      <td>
        <b>Number of Invoices This Year:</b>

      </td>

      <td>
        @Html.DisplayFor(model => model.numThisYear)
      </td>
    </tr>
    <tr>
      <td>
        <b>Total Invoices Outstanding:</b>
      </td>

      <td>
        @Html.DisplayFor(model => model.numOutstandingInvoices)
      </td>
    </tr>
    <tr>
      <td>
        <b>Total Revenue Outstanding (Value of Unpaid Invoices):</b>

      </td>

      <td>
        @Html.DisplayFor(model => model.moneyOutstanding)
      </td>
    </tr>
  </table>
</div>
<p>
  @Html.ActionLink("Back to List of Reports", "Index")
</p>

WorkOrderManagementSystem/WorkOrderManagementSystem/Views/Reports/ManufacturerPopularity.cshtml
@model List<WorkOrderManagementSystem.Controllers.ReportManufacturerPopularity>

@{
    ViewBag.Title = "Report: Manufacturer Popularity";
}

<h2>Report: Manufacturer Popularity</h2>
<h3>Sort</h3>
<table>
    <tr>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(0, 1, 0)">Manufacturer - Asc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(0, 0, 1)">Occurences - Asc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(0, 0, 2)">Avg Revenue - Asc</button> &nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(1, 1, 0)">Manufacturers - Desc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(1, 0, 1)">Occurences - Desc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(1, 0, 2)">Avg Revenue - Desc</button> &nbsp;&nbsp;&nbsp;</td>
    </tr>
</table>

<br />

<table id="reportTable" class="table">
    <tr>
        <th>
            Manufacturer
        </th>
        <th>
            Total Occurences
        </th>
        <th>
            Avg Revenue Per WO ($)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ManufacturerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManufacturerOccurences)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AvgRevenueGenerated)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script>
        // Parameters:
        // asc - 0 or 1 = true or false
        // isNum - 0 or 1 = true or false
        // tdIdx - column you want to sort the rows by (eg. by name, by price, etc.)
        function sortTable(asc, isNum, tdIdx) {
            var table, rows, switching, i, x, y, shouldSwitch;
            table = document.getElementById("reportTable");
            switching = true;
            /*Make a loop that will continue until
            no switching has been done:*/
            while (switching) {
                //start by saying: no switching is done:
                switching = false;
                rows = table.getElementsByTagName("TR");
                /*Loop through all table rows (except the
                first, which contains table headers):*/
                for (i = 1; i < (rows.length - 1) ; i++) {
                    //start by saying there should be no switching:
                    shouldSwitch = false;
                    /*Get the two elements you want to compare,
                    one from current row and one from the next:*/
                    x = rows[i].getElementsByTagName("TD")[tdIdx];
                    y = rows[i + 1].getElementsByTagName("TD")[tdIdx];
                    //check if the two rows should switch place:
                    if (asc === 0) {
                        if (isNum === 0) {
                            if (parseFloat(x.innerHTML) > parseFloat(y.innerHTML)) {
                                //if so, mark as a switch and break the loop:
                                shouldSwitch = true;
                                break;
                            }
                        } else {
                            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                                //if so, mark as a switch and break the loop:
                                shouldSwitch = true;
                                break;
                            }
                        }
                    } else {
                        if (isNum === 0) {
                            if (parseFloat(x.innerHTML) < parseFloat(y.innerHTML)) {
                                //if so, mark as a switch and break the loop:
                                shouldSwitch = true;
                                break;
                            }
                        } else {
                            if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                                //if so, mark as a switch and break the loop:
                                shouldSwitch = true;
                                break;
                            }
                        }
                    }
                }
                if (shouldSwitch) {
                    /*If a switch has been marked, make the switch
                    and mark that a switch has been done:*/
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                }
            }
        }
    </script>
}

WorkOrderManagementSystem/WorkOrderManagementSystem/Views/Reports/MechanicReports.cshtml
@model IEnumerable<WorkOrderManagementSystem.Controllers.ReportMechanicOrderTotals>

@{
    ViewBag.Title = "MechanicReports";
}

<h2>MechanicReports</h2>

<p>
  <button class="btn-group" type="button" name="weekly" onclick="getWeekly()">Week</button>
  <button class="btn-group" type="button" name="monthly" onclick="getMonthly()">Month</button>
  <button class="btn-group" type="button" name="yearly" onclick="getYearly()">Year</button>
</p>
<h1 id="timeHeading">Work Orders This Week:</h1>
<div id="fillMe">

  
  <table class="table">
    <tr>
      <td></td>
      <th>
        @Html.DisplayNameFor(model => model.inProgress)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.completed)
      </th>
      <th></th>
    </tr>

    @foreach (var item in Model)
    {
      <tr>
        <td>
          <table>
            <tr><th>Name</th><th>Email</th></tr>
            <tr><td>@item.mechanic.FirstName @item.mechanic.LastName</td><td>@item.mechanic.Email</td></tr>
          </table>
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.inProgress)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.completed)
        </td>
        <td>

          @Html.ActionLink("Mechanic Details","Details/"+ item.mechanic.Id, "Mechanics")
        </td>
      </tr>
    }

  </table>
</div>

<script>
  function getWeekly() {

    //var element = document.getElementById('#dropOff');
    // Get a reference to the DOM element
    var element = document.querySelector('#fillMe');// NOTE the '#' preceding the name of the div we're updating
    var heading = document.querySelector('#timeHeading');
    // create an xhr object
    var xhr = new XMLHttpRequest();

    // configure its handler
    xhr.onreadystatechange = function () {

      if (xhr.readyState === 4) {
        // request-response cycle has been completed, so continue

        if (xhr.status === 200) {
          // request was successfully completed, and data was received, so continue

          // update the user interface
          element.innerHTML = xhr.responseText;
          heading.innerHTML = "Work Orders This Week";


        } else {
          element.innerHTML = "<p>Request was not successful<br>(" + xhr.statusText + ")</p>";
        }
      } else {
        element.innerHTML = "<p>Loading...</p>";
      }
      // show the content
      element.style.display = 'block';
    }

    // configure the xhr object to fetch content
    xhr.open('GET', '/reports/MechAsgtWeekly', true);//TODO: ADDED GET style variable syntax to request URL to allow controller to recognize variable
    // fetch the content
    xhr.send(null);
  }
  function getMonthly() {

    //var element = document.getElementById('#dropOff');
    // Get a reference to the DOM element
    var element = document.querySelector('#fillMe');// NOTE the '#' preceding the name of the div we're updating
    var heading = document.querySelector('#timeHeading');

    // create an xhr object
    var xhr = new XMLHttpRequest();

    // configure its handler
    xhr.onreadystatechange = function () {

      if (xhr.readyState === 4) {
        // request-response cycle has been completed, so continue

        if (xhr.status === 200) {
          // request was successfully completed, and data was received, so continue

          // update the user interface
          element.innerHTML = xhr.responseText;
          heading.innerHTML = "Work Orders This Month";


        } else {
          element.innerHTML = "<p>Request was not successful<br>(" + xhr.statusText + ")</p>";
        }
      } else {
        element.innerHTML = "<p>Loading...</p>";
      }
      // show the content
      element.style.display = 'block';
    }

    // configure the xhr object to fetch content
    xhr.open('GET', '/reports/MechAsgtMonthly', true);//TODO: ADDED GET style variable syntax to request URL to allow controller to recognize variable
    // fetch the content
    xhr.send(null);
  }
  function getYearly() {

    //var element = document.getElementById('#dropOff');
    // Get a reference to the DOM element
    var element = document.querySelector('#fillMe');// NOTE the '#' preceding the name of the div we're updating
    var heading = document.querySelector('#timeHeading');

    // create an xhr object
    var xhr = new XMLHttpRequest();

    // configure its handler
    xhr.onreadystatechange = function () {

      if (xhr.readyState === 4) {
        // request-response cycle has been completed, so continue

        if (xhr.status === 200) {
          // request was successfully completed, and data was received, so continue

          // update the user interface
          element.innerHTML = xhr.responseText;
          heading.innerHTML = "Work Orders This Year";


        } else {
          element.innerHTML = "<p>Request was not successful<br>(" + xhr.statusText + ")</p>";
        }
      } else {
        element.innerHTML = "<p>Loading...</p>";
      }
      // show the content
      element.style.display = 'block';
    }

    // configure the xhr object to fetch content
    xhr.open('GET', '/reports/MechAsgtYearly', true);//TODO: ADDED GET style variable syntax to request URL to allow controller to recognize variable
    // fetch the content
    xhr.send(null);
  }
  </script>

WorkOrderManagementSystem/WorkOrderManagementSystem/Views/Reports/ServiceItemPopularity.cshtml
@model List<WorkOrderManagementSystem.Controllers.ReportServiceItemPopularity>

@{
    ViewBag.Title = "Report: Service Popularity";
}

<h2>Report: Service Popularity</h2>
<h3>Sort</h3>
<table>
    <tr>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(0, 1, 0)">Description - Asc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(0, 0, 1)">Price - Asc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(0, 0, 2)">Occurences - Asc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(0, 0, 3)">Revenue - Asc</button> &nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(1, 1, 0)">Description - Desc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(1, 0, 1)">Price - Desc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(1, 0, 2)">Occurences - Desc</button> &nbsp;&nbsp;&nbsp;</td>
        <td><button type="button" class="btn btn-primary" onclick="sortTable(1, 0, 3)">Revenue - Desc</button> &nbsp;&nbsp;&nbsp;</td>
    </tr>
</table>

<br />

<table id="reportTable" class="table">
    <tr>
        <th>
            Service Item Description
        </th>
        <th>
            Price
        </th>
        <th>
            Total Occurences
        </th>
        <th>
            Revenue Generated ($)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ServiceItemDesc)
        </td>
        <td id="SIPrice">
            @Html.DisplayFor(modelItem => item.ServiceItemPrice)
        </td>
        <td id="TotalOccurences">
            @Html.DisplayFor(modelItem => item.ServiceItemOccurences)
        </td>
        <td id="RevenueGen">
           @Html.DisplayFor(modelItem => item.RevenueGenerated)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script>
        // Parameters: 
        // asc - 0 or 1 = true or false
        // isNum - 0 or 1 = true or false
        // tdIdx - column you want to sort the rows by (eg. by name, by price, etc.)
        function sortTable(asc, isNum, tdIdx) {
            var table, rows, switching, i, x, y, shouldSwitch;
            table = document.getElementById("reportTable");
            switching = true;
            /*Make a loop that will continue until
            no switching has been done:*/
            while (switching) {
                //start by saying: no switching is done:
                switching = false;
                rows = table.getElementsByTagName("TR");
                /*Loop through all table rows (except the
                first, which contains table headers):*/
                for (i = 1; i < (rows.length - 1) ; i++) {
                    //start by saying there should be no switching:
                    shouldSwitch = false;
                    /*Get the two elements you want to compare,
                    one from current row and one from the next:*/
                    x = rows[i].getElementsByTagName("TD")[tdIdx];
                    y = rows[i + 1].getElementsByTagName("TD")[tdIdx];
                    //check if the two rows should switch place:
                    if (asc === 0) {
                        if (isNum === 0) {
                            if (parseInt(x.innerHTML) > parseInt(y.innerHTML)) {
                                //if so, mark as a switch and break the loop:
                                shouldSwitch = true;
                                break;
                            }
                        } else {
                            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                                //if so, mark as a switch and break the loop:
                                shouldSwitch = true;
                                break;
                            }
                        }
                    } else {
                        if (isNum === 0) {
                            if (parseInt(x.innerHTML) < parseInt(y.innerHTML)) {
                                //if so, mark as a switch and break the loop:
                                shouldSwitch = true;
                                break;
                            }
                        } else {
                            if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                                //if so, mark as a switch and break the loop:
                                shouldSwitch = true;
                                break;
                            }
                        }
                    } 
                }
                if (shouldSwitch) {
                    /*If a switch has been marked, make the switch
                    and mark that a switch has been done:*/
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                }
            }
        }
    </script>
}

WorkOrderManagementSystem/WorkOrderManagementSystem/Views/Reports/_MechAsgtWeek.cshtml
@model IEnumerable<WorkOrderManagementSystem.Controllers.ReportMechanicOrderTotals>


<table class="table">
    <tr>
      <td></td>
        <th>
            @Html.DisplayNameFor(model => model.inProgress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.completed)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
      <td>
       <table>
         <tr><th>Name</th><th>Email</th></tr>
         <tr><td>@item.mechanic.FirstName @item.mechanic.LastName</td><td>@item.mechanic.Email</td></tr>
       </table>
      </td>
        <td>
            @Html.DisplayFor(modelItem => item.inProgress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.completed)
        </td>
        <td>
            
          @Html.ActionLink("Mechanic Details", "Details/" + item.mechanic.Id, "Mechanics")


        </td>
    </tr>
}

</table>